name: Bicep-KQL-demo
trigger:
  branches:
    include:
    - master
    - main
  paths:
    include:
    - source/Demo.KQL.FunctionsNet6/Demo.KQL.FunctionsNet6
    - azure-pipelines-fnapp-2.yml

variables:
  resourceGroupName: 'kql-demo'
  location: 'westeurope'
  azureSubscription: 'Azure Mart MPN'
  resourcePrefix: 'bicep'
  # Azure Resource Manager connection created during pipeline creation
  # azureSubscription: '0788092a-a6d9-4a51-ad71-7d1a9e0bd299'

  # Function app name
  functionAppName: 'bicep-fnapp-2wej7bj-2'

  # Agent VM image name
  vmImageName: 'windows-2019'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/source/Demo.KQL.FunctionsNet6/Demo.KQL.FunctionsNet6'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'Demo'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionAppLinux
              appName: $(functionAppName)
              deploymentMethod: zipDeploy
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'